### PR TITLE
Add openrc init script

### PR DESCRIPTION
**Pull request by matthew-sharp**
I made this for my own use, feel free to take or decline it (or ask questions).

### CODE REVIEW

**Comment by tobixen** [comment]
thanks

**Comment by tobixen** [comment]
what OS is it for? (sorry if that's a silly question, I'm possibly living in my own "bubble")

**Comment by matthew-sharp** [comment]
Primarily Gentoo where it is the default (though systemd can be swapped in fairly easily), but also some more obscure distros. I've only tested it on gentoo but it should work on the others.

**Comment by tobixen** [comment]
Right, it was a stupid question as I anyway decided to google it right after asking the question :-)  I gave up gentoo more than a decade ago, had too many problems with it.  I used to say that all distros sucks - but some of them suck less than others, I'm actually fairly happy with Archlinux.

**Comment by matthew-sharp** [comment]
Arch would be the distro I try next if Gentoo dies. I agree that all distros suck, I would even go further and say that all OSes suck.

**Pull request merged**
